"""initial schema

Revision ID: 7c0f80cf19b3
Revises: 
Create Date: 2026-08-31 22:35:14.828994
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7c0f80cf19b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('record_id', sa.String(length=120), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index('ix_audit_username', 'audit_logs', ['username'], unique=False)
    op.create_table('beneficiaries',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('husband_name', sa.String(length=120), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('mobile_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('village', sa.String(length=80), nullable=True),
    sa.Column('block', sa.String(length=80), nullable=True),
    sa.Column('district', sa.String(length=80), nullable=True),
    sa.Column('blood_group', sa.String(length=4), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_beneficiaries_full_name', 'beneficiaries', ['full_name'], unique=False)
    op.create_index('ix_beneficiaries_mobile', 'beneficiaries', ['mobile_number'], unique=False)
    op.create_index('ix_beneficiaries_village', 'beneficiaries', ['village'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('Administrator', 'Health Worker', name='user_role'), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('phc_center', sa.String(length=120), nullable=True),
    sa.Column('sector', sa.String(length=80), nullable=True),
    sa.Column('assigned_villages', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('children',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('child_id', sa.String(length=40), nullable=False),
    sa.Column('beneficiary_id', sa.String(length=40), nullable=False),
    sa.Column('health_worker_id', sa.String(length=40), nullable=True),
    sa.Column('child_name', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', name='gender'), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('birth_weight', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('place_of_birth', sa.String(length=120), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('village', sa.String(length=80), nullable=True),
    sa.Column('block', sa.String(length=80), nullable=True),
    sa.Column('district', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['health_worker_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id')
    )
    op.create_index('ix_children_beneficiary', 'children', ['beneficiary_id'], unique=False)
    op.create_index('ix_children_created_at', 'children', ['created_at'], unique=False)
    op.create_index('ix_children_gender', 'children', ['gender'], unique=False)
    op.create_index('ix_children_village', 'children', ['village'], unique=False)
    op.create_index('ix_children_worker', 'children', ['health_worker_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='alert_priority'), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('beneficiary_name', sa.String(length=200), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('target_user_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notifications_target', 'notifications', ['target_user_id'], unique=False)
    op.create_table('pregnancies',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('beneficiary_id', sa.String(length=40), nullable=False),
    sa.Column('assigned_worker_id', sa.String(length=40), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('lmp', sa.Date(), nullable=False),
    sa.Column('edd', sa.Date(), nullable=True),
    sa.Column('trimester', sa.Integer(), nullable=True),
    sa.Column('gravida', sa.Integer(), nullable=True),
    sa.Column('para', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bp_systolic', sa.Integer(), nullable=True),
    sa.Column('bp_diastolic', sa.Integer(), nullable=True),
    sa.Column('hemoglobin', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('fundal_height', sa.String(length=20), nullable=True),
    sa.Column('fetal_heart_rate', sa.Integer(), nullable=True),
    sa.Column('is_high_risk', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('high_risk_reasons', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('previous_pregnancy_history', sa.Text(), nullable=True),
    sa.Column('existing_conditions', sa.Text(), nullable=True),
    sa.Column('risk_factors', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('active', 'high_risk', 'delivered', 'archived', name='pregnancy_status'), server_default='active', nullable=False),
    sa.Column('delivery_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sync_status', sa.String(length=20), server_default='synced', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_worker_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pregnancies_beneficiary', 'pregnancies', ['beneficiary_id'], unique=False)
    op.create_index('ix_pregnancies_created_at', 'pregnancies', ['created_at'], unique=False)
    op.create_index('ix_pregnancies_status', 'pregnancies', ['status'], unique=False)
    op.create_index('ix_pregnancies_status_high_risk', 'pregnancies', ['status', 'is_high_risk'], unique=False)
    op.create_index('ix_pregnancies_status_trimester', 'pregnancies', ['status', 'trimester'], unique=False)
    op.create_index('ix_pregnancies_worker', 'pregnancies', ['assigned_worker_id'], unique=False)
    op.create_table('sync_queue',
    sa.Column('client_txn_id', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('worker_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='PROCESSED', nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('client_txn_id')
    )
    op.create_index('ix_sync_queue_timestamp', 'sync_queue', ['timestamp'], unique=False)
    op.create_index('ix_sync_queue_worker', 'sync_queue', ['worker_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('alert_type', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='alert_priority'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_entity_type', sa.Enum('pregnancy', 'child', name='related_entity_type'), nullable=False),
    sa.Column('pregnancy_id', sa.String(length=40), nullable=True),
    sa.Column('child_id', sa.String(length=40), nullable=True),
    sa.Column('assigned_worker_id', sa.String(length=40), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED', name='alert_status'), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(related_entity_type = 'pregnancy' AND pregnancy_id IS NOT NULL AND child_id IS NULL) OR (related_entity_type = 'child' AND child_id IS NOT NULL AND pregnancy_id IS NULL)", name='ck_alerts_entity_ref'),
    sa.ForeignKeyConstraint(['assigned_worker_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pregnancy_id'], ['pregnancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_child', 'alerts', ['child_id'], unique=False)
    op.create_index('ix_alerts_pregnancy', 'alerts', ['pregnancy_id'], unique=False)
    op.create_index('ix_alerts_priority', 'alerts', ['priority'], unique=False)
    op.create_index('ix_alerts_status', 'alerts', ['status'], unique=False)
    op.create_index('ix_alerts_status_created', 'alerts', ['status', 'created_at'], unique=False)
    op.create_index('ix_alerts_status_type', 'alerts', ['status', 'alert_type'], unique=False)
    op.create_index('ix_alerts_type', 'alerts', ['alert_type'], unique=False)
    op.create_index('ix_alerts_worker', 'alerts', ['assigned_worker_id'], unique=False)
    op.create_table('anc_visits',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('pregnancy_id', sa.String(length=40), nullable=False),
    sa.Column('health_worker_id', sa.String(length=40), nullable=True),
    sa.Column('visit_number', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('next_visit_date', sa.Date(), nullable=True),
    sa.Column('gestational_weeks_at_visit', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bp_systolic', sa.Integer(), nullable=True),
    sa.Column('bp_diastolic', sa.Integer(), nullable=True),
    sa.Column('hemoglobin', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('fundal_height', sa.String(length=20), nullable=True),
    sa.Column('fetal_heart_rate', sa.Integer(), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('examination_notes', sa.Text(), nullable=True),
    sa.Column('investigation_details', sa.Text(), nullable=True),
    sa.Column('advice', sa.Text(), nullable=True),
    sa.Column('risk_status', sa.String(length=12), nullable=True),
    sa.Column('status', sa.Enum('Completed', 'Upcoming', 'Overdue', name='visit_status'), server_default='Completed', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['health_worker_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pregnancy_id'], ['pregnancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_anc_visits_pregnancy', 'anc_visits', ['pregnancy_id'], unique=False)
    op.create_index('ix_anc_visits_pregnancy_visitnum', 'anc_visits', ['pregnancy_id', 'visit_number'], unique=False)
    op.create_index('ix_anc_visits_status', 'anc_visits', ['status'], unique=False)
    op.create_index('ix_anc_visits_worker', 'anc_visits', ['health_worker_id'], unique=False)
    op.create_table('child_immunizations',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('child_id', sa.String(length=40), nullable=False),
    sa.Column('health_worker_id', sa.String(length=40), nullable=True),
    sa.Column('vaccine_code', sa.String(length=20), nullable=False),
    sa.Column('vaccine_name', sa.String(length=120), nullable=False),
    sa.Column('target_age_label', sa.String(length=40), nullable=True),
    sa.Column('recommended_due_date', sa.Date(), nullable=True),
    sa.Column('administered_date', sa.Date(), nullable=True),
    sa.Column('route', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('Upcoming', 'Due', 'Completed', 'Overdue', name='immunization_status'), server_default='Upcoming', nullable=False),
    sa.Column('batch_no', sa.String(length=40), nullable=True),
    sa.Column('adverse_event_reported', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['health_worker_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_child_imm_child', 'child_immunizations', ['child_id'], unique=False)
    op.create_index('ix_child_imm_child_status', 'child_immunizations', ['child_id', 'status'], unique=False)
    op.create_index('ix_child_imm_status', 'child_immunizations', ['status'], unique=False)
    op.create_table('maternal_immunizations',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('pregnancy_id', sa.String(length=40), nullable=False),
    sa.Column('health_worker_id', sa.String(length=40), nullable=True),
    sa.Column('vaccine_name', sa.String(length=80), nullable=False),
    sa.Column('dose', sa.String(length=40), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('recommended_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('administration_date', sa.Date(), nullable=True),
    sa.Column('batch_number', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('Upcoming', 'Due', 'Completed', 'Overdue', name='immunization_status'), server_default='Upcoming', nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['health_worker_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pregnancy_id'], ['pregnancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mat_imm_pregnancy', 'maternal_immunizations', ['pregnancy_id'], unique=False)
    op.create_index('ix_mat_imm_status', 'maternal_immunizations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mat_imm_status', table_name='maternal_immunizations')
    op.drop_index('ix_mat_imm_pregnancy', table_name='maternal_immunizations')
    op.drop_table('maternal_immunizations')
    op.drop_index('ix_child_imm_status', table_name='child_immunizations')
    op.drop_index('ix_child_imm_child_status', table_name='child_immunizations')
    op.drop_index('ix_child_imm_child', table_name='child_immunizations')
    op.drop_table('child_immunizations')
    op.drop_index('ix_anc_visits_worker', table_name='anc_visits')
    op.drop_index('ix_anc_visits_status', table_name='anc_visits')
    op.drop_index('ix_anc_visits_pregnancy_visitnum', table_name='anc_visits')
    op.drop_index('ix_anc_visits_pregnancy', table_name='anc_visits')
    op.drop_table('anc_visits')
    op.drop_index('ix_alerts_worker', table_name='alerts')
    op.drop_index('ix_alerts_type', table_name='alerts')
    op.drop_index('ix_alerts_status_type', table_name='alerts')
    op.drop_index('ix_alerts_status_created', table_name='alerts')
    op.drop_index('ix_alerts_status', table_name='alerts')
    op.drop_index('ix_alerts_priority', table_name='alerts')
    op.drop_index('ix_alerts_pregnancy', table_name='alerts')
    op.drop_index('ix_alerts_child', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_sync_queue_worker', table_name='sync_queue')
    op.drop_index('ix_sync_queue_timestamp', table_name='sync_queue')
    op.drop_table('sync_queue')
    op.drop_index('ix_pregnancies_worker', table_name='pregnancies')
    op.drop_index('ix_pregnancies_status_trimester', table_name='pregnancies')
    op.drop_index('ix_pregnancies_status_high_risk', table_name='pregnancies')
    op.drop_index('ix_pregnancies_status', table_name='pregnancies')
    op.drop_index('ix_pregnancies_created_at', table_name='pregnancies')
    op.drop_index('ix_pregnancies_beneficiary', table_name='pregnancies')
    op.drop_table('pregnancies')
    op.drop_index('ix_notifications_target', table_name='notifications')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_children_worker', table_name='children')
    op.drop_index('ix_children_village', table_name='children')
    op.drop_index('ix_children_gender', table_name='children')
    op.drop_index('ix_children_created_at', table_name='children')
    op.drop_index('ix_children_beneficiary', table_name='children')
    op.drop_table('children')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_beneficiaries_village', table_name='beneficiaries')
    op.drop_index('ix_beneficiaries_mobile', table_name='beneficiaries')
    op.drop_index('ix_beneficiaries_full_name', table_name='beneficiaries')
    op.drop_table('beneficiaries')
    op.drop_index('ix_audit_username', table_name='audit_logs')
    op.drop_index('ix_audit_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
